language: python

python:
  - "3.5"

env:
  - VERSION="12.0" LINT_CHECK="1"
  - VERSION="12.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"
  - VERSION="12.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
# either use the two lines above or the two below. Don't change the default if
# it's not necessary (it is only necessary if modules in your repository can't
# be installed in the same database. And you get a huge speed penalty in your
# tests)
#  - VERSION="12.0" ODOO_REPO="OCA/OCB" UNIT_TEST="1" LINT_CHECK="0"
#  - VERSION="12.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1" LINT_CHECK="0"


install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  coveralls
